PKGBUILDS/danctnix/numberstation/PKGBUILD
=> numberstation: new package

PKGBUILDS/danctnix/fcft/CHANGELOG.md, PKGBUILDS/danctnix/fcft/PKGBUILD, PKGBUILDS/danctnix/foot/0001-config-letter-spacing-add-missing-return.patch, PKGBUILDS/danctnix/foot/CHANGELOG.md, PKGBUILDS/danctnix/foot/PKGBUILD, PKGBUILDS/danctnix/tllist/PKGBUILD
Foot is the default terminal in sxmo / wayland and will be required for the sxmo 1.6 upgrade
=> Package the foot terminal emulator

PKGBUILDS/danctnix/mmsd-tng/PKGBUILD
This builds, and I don't think this should break anything, but I haven't run any sanity checks. I plan to do that tomorrow.
=> pkg: danctnix: mmsd-tng: upgrade to 1.6

PKGBUILDS/sxmo/sxmo-utils/0001-Let-systemd-handle-service-supervision.patch, PKGBUILDS/sxmo/sxmo-utils/PKGBUILD
I've been running this for a couple days, I'm inclined to give it a few more in case anyone else finds bugs in it.
Note to users: sxmo changed a bunch of the config files upstream this release, so things will break if you don't update your configuration, `sxmo_migrate.sh` should do that.
=> pkg: sxmo: sxmo-utils: upgrade to 1.8.0

PKGBUILDS/danctnix/mmsd-tng/PKGBUILD
Fixes #308, thanks for opening that. For some reason gitlab didn't notify me when the new version of mmsd was released.
=> pkg: danctnix: mmsd-tng: upgrade to 1.8

PKGBUILDS/danctnix/vvmd/PKGBUILD
Unfortunately my carrier seems to have changed something that breaks
vvmd, so I can't test this.
=> pkg: danctnix: vvmd: update to 0.8

PKGBUILDS/sxmo/sxmo-bemenu/PKGBUILD, PKGBUILDS/sxmo/sxmo-utils/PKGBUILD
Upstream bemenu has gotten the patches that sxmo needs
=> pkg: sxmo: sxmo-bemenu: turn into dummy package

PKGBUILDS/sxmo/codemadness-frontends/PKGBUILD
libretls got a upgrade which requires codemadness-frontends to be
rebuilt
=> pkg: sxmo: codemadness-frontends: bump pkgrel

PKGBUILDS/danctnix/osk-sdl/PKGBUILD, PKGBUILDS/danctnix/osk-sdl/fix-config-parsing-with-libstdc++.patch
From here: https://gitlab.com/postmarketOS/osk-sdl/-/commit/938e6b0c96b7cf2d3f169028b06a2cd36148416a
=> Change config parsing patch to officially accepted change

PKGBUILDS/phosh/chatty/PKGBUILD
=> pkg: phosh: chatty: upgrade to 0.6.6

PKGBUILDS/danctnix/mmsd-tng/PKGBUILD
validated by sending and receiving a picture through chatty
=> pkg: danctnix: mmsd-tng: upgrade to 1.11

PKGBUILDS/danctnix/vvmd/PKGBUILD
vvmd is currently broken with my carrier (t-mobile) so I can't fully test this, but it builds and runs
=> pkg: danctnix: vvmd: upgrade to 0.11

PKGBUILDS/danctnix/vvmplayer/PKGBUILD
vvmd is currently broken with my carrier (t-mobile) so I can't fully test this, but it builds and runs
=> pkg: danctnix: vvmplayer: upgrade to 1.5

PKGBUILDS/sxmo/sxmo-utils/PKGBUILD
I don't have a PP Pro, so if someone could verify this works it would be great
=> pkg: sxmo: sxmo-utils: fix power button identifier for PPP

PKGBUILDS/danctnix/mmsd-tng/PKGBUILD
Testing: Builds and runs, I sent and received a group text
=> pkg: danctnix: mmsd-tng: upgrade to 2.0.0

PKGBUILDS/phosh/phosh/PKGBUILD
Updated dependencies. Tested on my local machine.
=> pkg: phosh: phosh: upgrade to 0.23

PKGBUILDS/danctnix/vvmd/PKGBUILD
Builds and runs, but due to a bug with my carrier I can't test it fully
=> pkg: danctnix: vvmd: upgrade to 0.14

PKGBUILDS/sxmo/sxmo-utils/0001-avoid-conflicting-with-systemd-services.patch, PKGBUILDS/sxmo/sxmo-utils/0002-Fixup-icons-for-nerd-fonts-3.0.patch, PKGBUILDS/sxmo/sxmo-utils/0003-Manual-fixups-for-nerd-fonts-3.0.patch, PKGBUILDS/sxmo/sxmo-utils/0004-Fix-broken-printf-statements-in-modemtext.patch, PKGBUILDS/sxmo/sxmo-utils/0005-Don-t-kill-tailtextlog-when-changing-recipients.patch, PKGBUILDS/sxmo/sxmo-utils/0006-Update-fontconfig.conf-for-nerd-fonts-3.0.patch, PKGBUILDS/sxmo/sxmo-utils/PKGBUILD
I finally got around to fixing the mms issue that's been preventing this from moving to stable. I also updated a bunch of the icons so they work with nerd-fonts 3.0.
=> pkg: sxmo: sxmo-utils: add patches for mms and nerd-fonts 3.0

PKGBUILDS/danctnix/megapixels/PKGBUILD
This fixes Megapixels on newer kernels (#540)
=> pkg: danctnix: megapixels: upgrade to 1.6.1

PKGBUILDS/phosh/portfolio-file-manager/PKGBUILD
Portfolio was ported to GTK4 and libadwaita in this release
=> pkg: phosh: portfolio-file-manager: upgrade to 1.0.0
