dreemurrs-embedded/Pine64-Arch

PKGBUILDS/phosh/danctnix-phosh-ui-meta/PKGBUILD
PKGBUILDS/phosh/danctnix-phosh-ui-meta/gtk-qt-tweaks.sh

Replace GDK_BACKEND=wayland with MOZ_ENABLE_WAYLAND=1. See https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland#gtk3
This allows some programs - such as Emacs and Chromium - which aren't Wayland-native to be started with XWayland.

pkg: phosh: danctnix-phosh-ui-meta: unbreak gdk xwayland

---

PKGBUILDS/danctnix/siglo/PKGBUILD

Update siglo version, and add missing dependency `python-requests`, needed from 0.6.0 onwards

pkg: danctnix: siglo: upgrade to 0.6.1

---

PKGBUILDS/danctnix/siglo/PKGBUILD

siglo has just updated to 0.6.2, and now has a dependency on pyxdg

pkg: danctnix: siglo: upgrade to 0.6.2

---

PKGBUILDS/danctnix/siglo/PKGBUILD

Bump to 0.7.1.
Siglo as of 0.7.0 has the option of a systemd service, but I'm not sure if or how it should be installed? It's a basic service, so easily enough installed by the end user they wish to do so themselves.

pkg: danctnix: siglo: upgrade to 0.7.2

---

PKGBUILDS/danctnix/numberstation/PKGBUILD

The meson dependency was missing

Fix numberstation

---

PKGBUILDS/danctnix/mmsd-tng/PKGBUILD
PKGBUILDS/danctnix/mmsd-tng/mmsd-tng.install
PKGBUILDS/danctnix/mmsd-tng/mmsd-tng.service

This adds a package for mmsd-tng which is required for sxmo 1.6, and will be required when chatty 0.5 is released.
I lightly tested this with a git build of chatty and was able to send and receive group texts.

pkg: danctnix: mmsd-tng: add 1.5

---

PKGBUILDS/sxmo/pn/PKGBUILD

The current version of pn in the repo appears to be built against an old version of icu. While looking into it I decided to fix the errors reported by namcap.

pn package cleanup

---

PKGBUILDS/sxmo/sxmo-sway/PKGBUILD
PKGBUILDS/sxmo/sxmo-wlroots/PKGBUILD

Sway needs a new version to be compatible with api changes in wlroots, so it gets upgraded as well.

Upgrade sxmo-wlroots to 0.14.0.0

---

PKGBUILDS/sxmo/sxmo-utils/PKGBUILD

Notes for this release:
- the default editor has changed to vim, users who haven't configured an editor will need to install vim

pkg: sxmo: sxmo-utils: upgrade to 1.8.2

---

PKGBUILDS/danctnix/telegram-desktop/PKGBUILD

In Phosh you have to tap on "Show All Apps" as it thinks telegram-desktop is not a mobile friendly app.

pkg: danctnix: telegram-desktop: mark as mobile friendly

---

PKGBUILDS/sxmo/sxmo-utils/0001-Backport-PPP-deviceprofile-from-upstream.patch
PKGBUILDS/sxmo/sxmo-utils/0002-PPP-deviceprofile-set-SXMO_SPEAKER.patch
PKGBUILDS/sxmo/sxmo-utils/PKGBUILD

The name of the speaker (used by amixer) seems to be different on the PPP than the PinePhone. This includes the deviceprofile for the PPP (which isn't in a release yet) and uses it to set the speaker.
This is a temporary fix until sxmo switches to pipewire / pulseaudio, which will probably be in 1.9.
Fixes #340

pkg: sxmo: sxmo-utils: add PPP deviceprofile

---

PKGBUILDS/phosh/gnome-control-center-mobile/PKGBUILD

power-profiles-daemon was made an optional component of gnome-control-center in the main Arch package: https://github.com/archlinux/svntogit-packages/commit/d8fc51d2b6adcbd7989591ea7d88f971c01eea1e
I believe it should be made optional here for consistency. It will also allow someone to use tlp instead of power-profiles-daemon if they want to. You can't really use tlp with the current PKGBUILD because you can't uninstall power-profiles-daemon without uninstalling gnome-control-center-mobile and tlp and power-profiles-daemon conflict with each other.
I tried building the package and installing locally.
Testing (Done in Phosh):
1. Opened the Power section of the Settings app. It loaded fine and the  "Power Mode" section was there
2. Uninstalled power-profiles-daemon (masking and stopping it …

pkg: phosh: gnome-control-center-mobile: Make power-profiles-daemon optional

---

PKGBUILDS/sxmo/sxmo-utils/PKGBUILD

This adds `bc` as a dependency for sxmo-utils. This is needed because version 1.8.2 does not source sxmo_common.sh, which defines `alias bc=busybox bc`.

pkg: sxmo: sxmo-utils: Add bc dependency

---

PKGBUILDS/sxmo/sfeed/PKGBUILD

Update sfeed to latest version from the AUR. Version 1.5 provides `sfeed-curses`, a dependency of the `f_rss` script.

pkg: sxmo: sfeed: update to 1.5

---

PKGBUILDS/sxmo/wayout/PKGBUILD

This version fixes an issue in sxmo where the clock would often be one minute behind.
Tested: building in a clean chroot, and running with the sxmo desktop widget script

pkg: sxmo: wayout: upgrade to 0.1.3

---

PKGBUILDS/danctnix/eg25-manager/PKGBUILD

This is the third (and hopefully last) update to the udev rules to detect the community firmware.
Smoke test:
- udev rules are applied to OGPP with community firmware
- the modem starts

pkg: danctnix: eg25-manager: upgrade to 0.4.6

---

PKGBUILDS/danctnix/mobile-config-firefox/PKGBUILD

Hi, 
here is another tiny bump for mobile-config-firefox (the .1 fixes a bug on older Phosh/wlroots that did not affect Arch, and as a positive side effect, also fixes the translation popup width for everybody). 
I've tested this on my PinePhone and PinePhone Pro.
Thank you!
Cheers,
Peter

pkg: danctnix: mobile-config-firefox: upgrade to 4.3.1

---

PKGBUILDS/danctnix/mobile-config-firefox/PKGBUILD

Hi, 
thanks for your continued work on Arch Linux for PINE64 devices! 
Here's another bump of mobile-config-firefox:
From the release notes:
Release 4.3.2
Fixes:
* policies.json: No longer hard-remove Google (MR 49)
* tabmenu.css: Fix private browsing mode (MR 51)
* appMenu.css: Adjust appMenu.css for Firefox 127 (MR 50)
I have tested it, and confirmed that it works. Since 127 is already in Arch Linux ARM, this fixes an existing issue with the appMenu and it would be great if it could land quickly!

pkg: danctnix: mobile-config-firefox: upgrade to 4.3.2

---

PKGBUILDS/sxmo/sxmo-utils/PKGBUILD

Upstream pipewire now provides pulse-native-provider instead of pulseaudio.

pkg: sxmo: sxmo-utils: fix pulseaudio dependency

---

PKGBUILDS/plasma/plasma-dialer/PKGBUILD

The qt6-quickcontrols2 package has been integrated into the qt6-declarative package. Therefore, it should be removed as a dependency for the plasma-dialer package.
Supporting links:
[https://github.com/qt/qtquickcontrols2?tab=readme-ov-file](https://github.com/qt/qtquickcontrols2?tab=readme-ov-file)
[https://bugreports.qt.io/browse/QTBUG-79454](https://bugreports.qt.io/browse/QTBUG-79454)
[https://wiki.qt.io/QtCS2021_-_Testing_upstream_changes_with_downstream_modules](https://wiki.qt.io/QtCS2021_-_Testing_upstream_changes_with_downstream_modules)
This resolves issue #668 
Once I removed the dependency, plasma-dialer built successfully on my x86_64 machine running Arch Linux.
I have done my best to adhere to the contribution guidelines. Hopefully I did not miss anything.

pkg: plasma: plasma-dialer: remove qt6-quickcontrols2 dependency

---

PKGBUILDS/danctnix/osk-sdl/PKGBUILD
PKGBUILDS/danctnix/osk-sdl/osk-sdl-install

Issue Description:
Pinephone after upgraded the whole system at around 2024-12-14Z, osk-sdl (used to unlock FDE (Full Disk Encryption)) does not start and outputs the following error:
```
MESA-LOADER: failed to open dri: /usr/lib/gbm/dri_gbm.so: cannnot open shared object file:
No such file or directory (search paths /usr/lib/gbm, suffix _gbm)
ERROR: Could not create window/display: EGL not initialized
```
How to reproduce:
Make sure you had a working FDE with osk-sdl in the past, you can use old packages from
http://tardis.tiny-vps.com/aarm/repos/2024/12/03/aarch64/core and http://tardis.tiny-vps.com/aarm/repos/2024/12/03/aarch64/extra archives by adding those links to /etc/pacman.conf to configure FDE to make sure FDE works with old mesa version 1:24.2.7-1. Then you remove those archive …

pkg: osk-sdl: fix pinephone osk-sdl regression mesa can't open /usr/lib/gbm/dri_gbm.so error
